const QUESTION_BANK = [
  {
    level: 'iniciante',
    category: 'variaveis',
    type: 'multiple',
    difficulty: 1,
    question: 'Qual palavra-chave é indicada para declarar uma variável que vai receber um novo valor mais adiante?',
    options: ['const', 'let', 'class', 'final'],
    answer: 1,
    explanation: 'let cria uma variável de bloco que aceita reatribuição. const impede a reatribuição e as outras nem existem para isso.'
  },
  {
    level: 'iniciante',
    category: 'variaveis',
    type: 'multiple',
    difficulty: 1,
    question: 'O que acontece quando este trecho é executado?',
    code: 'const nota = 7;\nnota = 9;',
    options: ['nota passa a valer 9', 'nota vira undefined', 'Um TypeError é lançado', 'O código roda sem nenhum efeito'],
    answer: 2,
    explanation: 'Reatribuir uma constante lança TypeError: Assignment to constant variable.'
  },
  {
    level: 'iniciante',
    category: 'variaveis',
    type: 'multiple',
    difficulty: 1,
    question: 'Qual nome de variável é válido em JavaScript?',
    options: ['2jogador', 'jogador-1', 'jogadorUm', 'let'],
    answer: 2,
    explanation: 'Nomes não podem começar com número, não aceitam hífen e não podem ser palavras reservadas como let.'
  },
  {
    level: 'iniciante',
    category: 'escopo',
    type: 'multiple',
    difficulty: 2,
    question: 'O que o console mostra?',
    code: 'if (true) {\n  let pontos = 10;\n}\nconsole.log(pontos);',
    options: ['10', 'undefined', 'null', 'ReferenceError'],
    answer: 3,
    explanation: 'let existe apenas dentro do bloco onde foi declarado, então fora dele a variável nem chega a existir.'
  },
  {
    level: 'iniciante',
    category: 'tipos',
    type: 'input',
    difficulty: 1,
    question: 'Qual texto aparece no console?',
    code: 'console.log(typeof "42");',
    answer: 'string',
    accept: ['string'],
    explanation: 'Mesmo contendo dígitos, o valor está entre aspas, então o tipo é string.'
  },
  {
    level: 'iniciante',
    category: 'tipos',
    type: 'multiple',
    difficulty: 2,
    question: 'Qual é o resultado de typeof null?',
    options: ['null', 'object', 'undefined', 'boolean'],
    answer: 1,
    explanation: 'typeof null devolve object por causa de um erro histórico da linguagem que foi mantido por compatibilidade.'
  },
  {
    level: 'iniciante',
    category: 'tipos',
    type: 'input',
    difficulty: 1,
    question: 'Qual número é impresso?',
    code: 'console.log(Number("7") + 1);',
    answer: '8',
    accept: ['8'],
    explanation: 'Number converte o texto para número antes da soma, por isso o resultado é 8 e não 71.'
  },
  {
    level: 'iniciante',
    category: 'numeros',
    type: 'multiple',
    difficulty: 1,
    question: 'O que aparece no console?',
    code: 'console.log("5" + 3);',
    options: ['8', '53', 'NaN', 'Erro de tipo'],
    answer: 1,
    explanation: 'Com uma string de um lado, o operador + concatena em vez de somar, gerando o texto 53.'
  },
  {
    level: 'iniciante',
    category: 'numeros',
    type: 'input',
    difficulty: 2,
    question: 'Qual valor é impresso?',
    code: 'console.log("10" - 3);',
    answer: '7',
    accept: ['7'],
    explanation: 'O operador - não concatena, então a string é convertida para número e a conta resulta em 7.'
  },
  {
    level: 'iniciante',
    category: 'numeros',
    type: 'input',
    difficulty: 1,
    question: 'Qual é o resultado de 10 % 3?',
    answer: '1',
    accept: ['1'],
    explanation: 'O operador % devolve o resto da divisão: 10 dividido por 3 dá 3 com resto 1.'
  },
  {
    level: 'iniciante',
    category: 'numeros',
    type: 'multiple',
    difficulty: 2,
    question: 'O que este código imprime?',
    code: 'console.log(0.1 + 0.2 === 0.3);',
    options: ['true', 'false', 'NaN', 'undefined'],
    answer: 1,
    explanation: 'Números decimais usam ponto flutuante binário: 0.1 + 0.2 dá 0.30000000000000004, diferente de 0.3.'
  },
  {
    level: 'iniciante',
    category: 'operadores',
    type: 'input',
    difficulty: 1,
    question: 'Qual valor é impresso?',
    code: 'let pontos = 5;\npontos += 3;\nconsole.log(pontos);',
    answer: '8',
    accept: ['8'],
    explanation: 'pontos += 3 é a forma curta de pontos = pontos + 3.'
  },
  {
    level: 'iniciante',
    category: 'operadores',
    type: 'multiple',
    difficulty: 1,
    question: 'Qual operador representa o E lógico, exigindo que as duas condições sejam verdadeiras?',
    options: ['&&', '||', '!', '=='],
    answer: 0,
    explanation: '&& é o E lógico, || é o OU lógico e ! inverte um valor booleano.'
  },
  {
    level: 'iniciante',
    category: 'comparacao',
    type: 'multiple',
    difficulty: 2,
    question: 'Qual das comparações abaixo resulta em false?',
    options: ['"5" == 5', '5 === 5', '"5" === 5', '5 != "6"'],
    answer: 2,
    explanation: '=== compara valor e tipo. A string "5" nunca é estritamente igual ao número 5.'
  },
  {
    level: 'iniciante',
    category: 'comparacao',
    type: 'input',
    difficulty: 1,
    question: 'Qual valor é impresso?',
    code: 'console.log(3 !== "3");',
    answer: 'true',
    accept: ['true'],
    explanation: '!== compara valor e tipo. Número e string são tipos diferentes, então eles são estritamente diferentes.'
  },
  {
    level: 'iniciante',
    category: 'strings',
    type: 'input',
    difficulty: 1,
    question: 'Qual número é impresso?',
    code: 'console.log("JavaScript".length);',
    answer: '10',
    accept: ['10'],
    explanation: 'length conta os caracteres da string, e JavaScript tem 10 letras.'
  },
  {
    level: 'iniciante',
    category: 'strings',
    type: 'multiple',
    difficulty: 1,
    question: 'Qual sintaxe insere o valor de uma variável dentro de um texto?',
    options: ['"Ola, " + ${nome}', '`Ola, ${nome}`', '"Ola, $nome"', '"Ola, {nome}"'],
    answer: 1,
    explanation: 'Template literals usam crases e ${} para interpolar valores dentro do texto.'
  },
  {
    level: 'iniciante',
    category: 'strings',
    type: 'input',
    difficulty: 2,
    question: 'Qual texto é impresso?',
    code: 'console.log("JavaScript".slice(0, 4));',
    answer: 'Java',
    accept: ['java'],
    explanation: 'slice(0, 4) pega do índice 0 até antes do índice 4, devolvendo Java.'
  },
  {
    level: 'iniciante',
    category: 'strings',
    type: 'multiple',
    difficulty: 2,
    question: 'O que acontece com a variável original?',
    code: 'const nome = "ana";\nnome.toUpperCase();\nconsole.log(nome);',
    options: ['ANA', 'ana', 'undefined', 'TypeError'],
    answer: 1,
    explanation: 'Strings são imutáveis: toUpperCase devolve um novo texto e o valor original continua igual.'
  },
  {
    level: 'iniciante',
    category: 'booleanos',
    type: 'multiple',
    difficulty: 2,
    question: 'Qual destes valores é falsy, ou seja, tratado como falso em uma condição?',
    options: ['"0"', '[]', '0', '{}'],
    answer: 2,
    explanation: 'O número 0 é falsy. A string "0", o array vazio e o objeto vazio são todos truthy.'
  },
  {
    level: 'iniciante',
    category: 'booleanos',
    type: 'input',
    difficulty: 2,
    question: 'Qual valor é impresso?',
    code: 'console.log(Boolean(""));',
    answer: 'false',
    accept: ['false'],
    explanation: 'Texto vazio é um dos valores falsy da linguagem, junto de 0, null, undefined e NaN.'
  },
  {
    level: 'iniciante',
    category: 'condicionais',
    type: 'multiple',
    difficulty: 1,
    question: 'Qual mensagem aparece no console?',
    code: 'const idade = 16;\nif (idade >= 18) {\n  console.log("Maior de idade");\n} else {\n  console.log("Menor de idade");\n}',
    options: ['Maior de idade', 'Menor de idade', 'As duas mensagens', 'Nenhuma mensagem'],
    answer: 1,
    explanation: '16 não é maior ou igual a 18, então o bloco else é executado.'
  },
  {
    level: 'iniciante',
    category: 'condicionais',
    type: 'input',
    difficulty: 2,
    question: 'Qual palavra é impressa?',
    code: 'const nota = 7;\nif (nota >= 9) {\n  console.log("otimo");\n} else if (nota >= 6) {\n  console.log("bom");\n} else {\n  console.log("ruim");\n}',
    answer: 'bom',
    accept: ['bom'],
    explanation: 'A primeira condição falha, a segunda é verdadeira e a cadeia para na primeira que der certo.'
  },
  {
    level: 'iniciante',
    category: 'funcoes',
    type: 'input',
    difficulty: 1,
    question: 'Qual número é impresso?',
    code: 'function dobro(valor) {\n  return valor * 2;\n}\nconsole.log(dobro(7));',
    answer: '14',
    accept: ['14'],
    explanation: 'O argumento 7 chega no parâmetro valor e a função devolve 7 * 2.'
  },
  {
    level: 'iniciante',
    category: 'funcoes',
    type: 'multiple',
    difficulty: 2,
    question: 'O que aparece no console, na ordem?',
    code: 'function saudacao(nome) {\n  console.log("Ola " + nome);\n}\nconst retorno = saudacao("Ana");\nconsole.log(retorno);',
    options: ['Ola Ana e depois undefined', 'Ola Ana duas vezes', 'undefined e depois Ola Ana', 'Ola Ana e depois null'],
    answer: 0,
    explanation: 'Uma função sem return devolve undefined, mesmo que ela imprima algo na tela.'
  },
  {
    level: 'iniciante',
    category: 'funcoes',
    type: 'multiple',
    difficulty: 2,
    question: 'Qual linha declara corretamente uma arrow function que soma dois valores?',
    options: ['const soma = (a, b) => a + b;', 'const soma = function[a, b] { a + b };', 'function => soma(a, b) { return a + b; }', 'const soma = (a, b) -> a + b;'],
    answer: 0,
    explanation: 'A sintaxe é parâmetros, seta e corpo. Sem chaves, o valor da expressão já é retornado.'
  },
  {
    level: 'iniciante',
    category: 'funcoes',
    type: 'input',
    difficulty: 2,
    question: 'Qual texto é impresso?',
    code: 'function saudar(nome = "visitante") {\n  return "Ola " + nome;\n}\nconsole.log(saudar());',
    answer: 'Ola visitante',
    accept: ['ola visitante'],
    explanation: 'Sem argumento, o parâmetro assume o valor padrão definido na declaração.'
  },
  {
    level: 'iniciante',
    category: 'arrays',
    type: 'input',
    difficulty: 1,
    question: 'Em um array, qual é o índice do primeiro elemento?',
    answer: '0',
    accept: ['0'],
    explanation: 'Arrays começam no índice 0, então o último elemento fica em length - 1.'
  },
  {
    level: 'iniciante',
    category: 'arrays',
    type: 'input',
    difficulty: 1,
    question: 'Qual número é impresso?',
    code: 'const cores = ["azul", "verde"];\ncores.push("amarelo");\nconsole.log(cores.length);',
    answer: '3',
    accept: ['3'],
    explanation: 'push adiciona o item no final do array, que passa a ter três elementos.'
  },
  {
    level: 'iniciante',
    category: 'arrays',
    type: 'multiple',
    difficulty: 2,
    question: 'Qual expressão acessa o último elemento de um array chamado lista, seja qual for o tamanho dele?',
    options: ['lista[lista.length]', 'lista[lista.length - 1]', 'lista.last', 'lista[-1]'],
    answer: 1,
    explanation: 'Como o índice começa em 0, o último elemento fica sempre em length - 1.'
  },
  {
    level: 'iniciante',
    category: 'arrays',
    type: 'input',
    difficulty: 1,
    question: 'Qual letra é impressa?',
    code: 'console.log(["a", "b", "c"][1]);',
    answer: 'b',
    accept: ['b'],
    explanation: 'O índice 1 aponta para o segundo elemento do array.'
  },

  {
    level: 'intermediario',
    category: 'metodos',
    type: 'multiple',
    difficulty: 2,
    question: 'O que é impresso?',
    code: 'const numeros = [1, 2, 3];\nconsole.log(numeros.map(n => n * 2));',
    options: ['[2, 4, 6]', '[1, 2, 3]', '6', '[1, 4, 9]'],
    answer: 0,
    explanation: 'map cria um novo array aplicando a função em cada item, sem alterar o array original.'
  },
  {
    level: 'intermediario',
    category: 'metodos',
    type: 'input',
    difficulty: 2,
    question: 'Qual número é impresso?',
    code: 'const numeros = [4, 9, 12, 7];\nconst grandes = numeros.filter(n => n > 8);\nconsole.log(grandes.length);',
    answer: '2',
    accept: ['2'],
    explanation: 'filter mantém apenas os itens que passam no teste: 9 e 12.'
  },
  {
    level: 'intermediario',
    category: 'metodos',
    type: 'input',
    difficulty: 2,
    question: 'Qual valor é impresso?',
    code: 'const usuarios = [{ id: 1 }, { id: 2 }];\nconsole.log(usuarios.find(usuario => usuario.id === 3));',
    answer: 'undefined',
    accept: ['undefined'],
    explanation: 'find devolve o primeiro item que satisfaz a condição ou undefined quando nenhum satisfaz.'
  },
  {
    level: 'intermediario',
    category: 'metodos',
    type: 'input',
    difficulty: 3,
    question: 'Qual número é impresso?',
    code: 'const valores = [2, 4, 6];\nconst total = valores.reduce((soma, item) => soma + item, 0);\nconsole.log(total);',
    answer: '12',
    accept: ['12'],
    explanation: 'reduce acumula os itens em um único valor partindo do acumulador inicial 0.'
  },
  {
    level: 'intermediario',
    category: 'metodos',
    type: 'multiple',
    difficulty: 2,
    question: 'O que forEach devolve?',
    options: ['Um novo array com os resultados', 'undefined', 'O array original', 'A quantidade de itens percorridos'],
    answer: 1,
    explanation: 'forEach apenas executa a função para cada item. Quando você precisa do resultado, use map.'
  },
  {
    level: 'intermediario',
    category: 'metodos',
    type: 'multiple',
    difficulty: 3,
    question: 'O que é impresso?',
    code: 'const numeros = [10, 9, 1];\nconsole.log(numeros.sort());',
    options: ['[1, 9, 10]', '[1, 10, 9]', '[10, 9, 1]', '[9, 10, 1]'],
    answer: 1,
    explanation: 'Sem função de comparação, sort converte os itens em texto e ordena alfabeticamente: "1", "10", "9".'
  },
  {
    level: 'intermediario',
    category: 'metodos',
    type: 'multiple',
    difficulty: 3,
    question: 'Qual afirmação sobre slice e splice está correta?',
    options: ['Os dois criam um novo array sem tocar no original', 'slice altera o array original e splice não', 'splice altera o array original e slice devolve uma cópia do trecho', 'Os dois alteram o array original'],
    answer: 2,
    explanation: 'splice remove ou insere itens no próprio array. slice apenas copia um pedaço para um novo array.'
  },
  {
    level: 'intermediario',
    category: 'metodos',
    type: 'input',
    difficulty: 2,
    question: 'Qual texto é impresso?',
    code: 'console.log(["a", "b", "c"].join("-"));',
    answer: 'a-b-c',
    accept: ['a-b-c'],
    explanation: 'join junta os itens do array em uma string usando o separador informado.'
  },
  {
    level: 'intermediario',
    category: 'objetos',
    type: 'input',
    difficulty: 2,
    question: 'Qual valor é impresso?',
    code: 'const jogador = { nome: "Ana", nivel: 3 };\nconst chave = "nivel";\nconsole.log(jogador[chave]);',
    answer: '3',
    accept: ['3'],
    explanation: 'Com colchetes a propriedade é escolhida pelo valor da variável. Com ponto, o nome seria literalmente chave.'
  },
  {
    level: 'intermediario',
    category: 'objetos',
    type: 'input',
    difficulty: 2,
    question: 'Qual número é impresso?',
    code: 'const config = { som: true, tela: "cheia" };\nconsole.log(Object.keys(config).length);',
    answer: '2',
    accept: ['2'],
    explanation: 'Object.keys devolve um array com os nomes das propriedades próprias do objeto.'
  },
  {
    level: 'intermediario',
    category: 'objetos',
    type: 'multiple',
    difficulty: 3,
    question: 'O que acontece?',
    code: 'const config = { tela: { largura: 480 } };\nconsole.log(config.tela.altura);',
    options: ['undefined', 'null', 'TypeError', '0'],
    answer: 0,
    explanation: 'tela existe, então acessar uma propriedade inexistente dentro dele devolve undefined em vez de erro.'
  },
  {
    level: 'intermediario',
    category: 'objetos',
    type: 'input',
    difficulty: 3,
    question: 'Qual número é impresso?',
    code: 'const perfil = { nome: "Ana" };\nperfil.nivel = 2;\nconsole.log(Object.keys(perfil).length);',
    answer: '2',
    accept: ['2'],
    explanation: 'const impede trocar a referência, mas não congela o conteúdo: dá para adicionar propriedades normalmente.'
  },
  {
    level: 'intermediario',
    category: 'loops',
    type: 'input',
    difficulty: 2,
    question: 'Qual número é impresso?',
    code: 'let total = 0;\nfor (let i = 1; i <= 4; i += 1) {\n  total += i;\n}\nconsole.log(total);',
    answer: '10',
    accept: ['10'],
    explanation: 'O laço soma 1, 2, 3 e 4, resultando em 10.'
  },
  {
    level: 'intermediario',
    category: 'loops',
    type: 'input',
    difficulty: 2,
    question: 'Qual número é impresso?',
    code: 'let vidas = 3;\nwhile (vidas > 0) {\n  vidas -= 1;\n}\nconsole.log(vidas);',
    answer: '0',
    accept: ['0'],
    explanation: 'O while só para quando a condição fica falsa, ou seja, quando vidas chega a 0.'
  },
  {
    level: 'intermediario',
    category: 'loops',
    type: 'multiple',
    difficulty: 3,
    question: 'Quais números são impressos?',
    code: 'for (const n of [1, 2, 3, 4]) {\n  if (n === 2) continue;\n  if (n === 4) break;\n  console.log(n);\n}',
    options: ['1 2 3', '1 3', '1 3 4', '1 2 3 4'],
    answer: 1,
    explanation: 'continue pula apenas a volta atual e break encerra o laço antes de imprimir o 4.'
  },
  {
    level: 'intermediario',
    category: 'loops',
    type: 'multiple',
    difficulty: 2,
    question: 'Ao percorrer um array, o que for...in entrega em cada volta?',
    options: ['Os valores dos itens', 'Os índices como texto', 'Pares no formato [indice, valor]', 'O array inteiro'],
    answer: 1,
    explanation: 'for...in percorre chaves, por isso em arrays ele devolve índices. Para valores use for...of.'
  },
  {
    level: 'intermediario',
    category: 'loops',
    type: 'input',
    difficulty: 2,
    question: 'Qual valor é impresso na primeira volta?',
    code: 'for (const cor of ["azul", "verde"]) {\n  console.log(cor);\n  break;\n}',
    answer: 'azul',
    accept: ['azul'],
    explanation: 'for...of entrega o valor de cada item, e o break encerra o laço logo na primeira volta.'
  },
  {
    level: 'intermediario',
    category: 'dom',
    type: 'multiple',
    difficulty: 2,
    question: 'O que document.querySelector(".item") devolve quando existem três elementos com essa classe?',
    options: ['Um array com os três elementos', 'O primeiro elemento encontrado', 'Uma NodeList com os três', 'null'],
    answer: 1,
    explanation: 'querySelector devolve o primeiro elemento correspondente, ou null quando não encontra nada.'
  },
  {
    level: 'intermediario',
    category: 'dom',
    type: 'multiple',
    difficulty: 3,
    question: 'Por que este código quebra?',
    code: 'const itens = document.querySelectorAll(".item");\nconst textos = itens.map(item => item.textContent);',
    options: ['querySelectorAll devolve uma NodeList, que não tem map', 'textContent não existe em elementos', 'Faltou usar await', 'map só funciona com números'],
    answer: 0,
    explanation: 'NodeList tem forEach, mas não map. Converta antes com Array.from(itens) ou [...itens].'
  },
  {
    level: 'intermediario',
    category: 'dom',
    type: 'multiple',
    difficulty: 2,
    question: 'Você precisa mostrar um texto digitado pelo usuário dentro de um elemento. Qual propriedade é a escolha correta?',
    options: ['innerHTML, porque aceita qualquer conteúdo', 'textContent, porque trata o valor como texto puro', 'outerHTML, porque substitui o elemento', 'value, porque guarda o conteúdo visível'],
    answer: 1,
    explanation: 'textContent insere o valor como texto e não interpreta tags, evitando injeção de HTML.'
  },
  {
    level: 'intermediario',
    category: 'dom',
    type: 'multiple',
    difficulty: 2,
    question: 'O que element.classList.toggle("ativo") faz?',
    options: ['Adiciona a classe sempre', 'Remove a classe sempre', 'Adiciona se não existir e remove se existir', 'Substitui todas as classes por ativo'],
    answer: 2,
    explanation: 'toggle alterna a presença da classe e ainda devolve true quando a classe ficou aplicada.'
  },
  {
    level: 'intermediario',
    category: 'dom',
    type: 'multiple',
    difficulty: 2,
    question: 'O botão tem o atributo data-nivel="3". O que console.log(botao.dataset.nivel) imprime?',
    options: ['3 como número', '"3" como string', 'undefined', 'null'],
    answer: 1,
    explanation: 'Atributos data sempre chegam como texto. Converta com Number quando precisar fazer contas.'
  },
  {
    level: 'intermediario',
    category: 'eventos',
    type: 'multiple',
    difficulty: 2,
    question: 'Qual linha registra corretamente a função salvar para o clique do botão?',
    options: ['botao.addEventListener("click", salvar())', 'botao.addEventListener("click", salvar)', 'botao.addEventListener(salvar, "click")', 'botao.addEventListener("click") = salvar'],
    answer: 1,
    explanation: 'Passe a referência da função. Com parênteses a função executa na hora e o retorno vira o ouvinte.'
  },
  {
    level: 'intermediario',
    category: 'eventos',
    type: 'multiple',
    difficulty: 3,
    question: 'Uma lista tem um único ouvinte de clique. Dentro do handler, o que event.target representa?',
    options: ['Sempre a lista que registrou o ouvinte', 'O elemento exato que recebeu o clique', 'O primeiro filho da lista', 'O documento inteiro'],
    answer: 1,
    explanation: 'event.target é quem originou o evento e event.currentTarget é quem registrou o ouvinte. Essa diferença sustenta a delegação.'
  },
  {
    level: 'intermediario',
    category: 'eventos',
    type: 'multiple',
    difficulty: 3,
    question: 'Por que removeEventListener não funciona aqui?',
    code: 'botao.addEventListener("click", () => salvar());\nbotao.removeEventListener("click", () => salvar());',
    options: ['Falta o terceiro argumento', 'As duas arrow functions são objetos diferentes', 'removeEventListener só aceita eventos de teclado', 'O evento precisa ser removido antes de ser adicionado'],
    answer: 1,
    explanation: 'Para remover é preciso passar exatamente a mesma referência de função usada no registro.'
  },
  {
    level: 'intermediario',
    category: 'formularios',
    type: 'multiple',
    difficulty: 2,
    question: 'Qual é o efeito de event.preventDefault() dentro do handler de submit de um formulário?',
    options: ['Impede o envio e o recarregamento da página', 'Limpa todos os campos', 'Bloqueia o envio apenas se houver erro', 'Impede o evento de subir para os elementos pais'],
    answer: 0,
    explanation: 'preventDefault cancela o comportamento padrão do navegador. Quem impede a propagação é stopPropagation.'
  },
  {
    level: 'intermediario',
    category: 'formularios',
    type: 'input',
    difficulty: 2,
    question: 'O usuário digitou 10 no campo. Qual texto é impresso?',
    code: 'const campo = document.querySelector("#quantidade");\nconsole.log(typeof campo.value);',
    answer: 'string',
    accept: ['string'],
    explanation: 'O valor de um input é sempre texto. Use Number ou parseInt antes de calcular.'
  },
  {
    level: 'intermediario',
    category: 'callbacks',
    type: 'multiple',
    difficulty: 3,
    question: 'O que é impresso?',
    code: 'function processar(lista, acao) {\n  return lista.map(acao);\n}\nconsole.log(processar([1, 2], n => n + 10));',
    options: ['[11, 12]', '[1, 2]', '[10, 10]', 'undefined'],
    answer: 0,
    explanation: 'A função recebida como callback é aplicada a cada item, e map devolve o novo array.'
  },
  {
    level: 'intermediario',
    category: 'metodos',
    type: 'multiple',
    difficulty: 3,
    question: 'O que é impresso?',
    code: 'const precos = [10, 25, 40];\nconsole.log(precos.filter(p => p >= 25).map(p => p * 2));',
    options: ['[20, 50, 80]', '[50, 80]', '[25, 40]', '[10, 25, 40]'],
    answer: 1,
    explanation: 'Primeiro o filter mantém 25 e 40, depois o map dobra cada um dos itens restantes.'
  },
  {
    level: 'intermediario',
    category: 'objetos',
    type: 'multiple',
    difficulty: 3,
    question: 'O que este trecho conta?',
    code: 'const votos = ["sim", "nao", "sim"];\nconst total = votos.reduce((contagem, voto) => {\n  contagem[voto] = (contagem[voto] || 0) + 1;\n  return contagem;\n}, {});\nconsole.log(total.sim);',
    options: ['1', '2', '3', 'undefined'],
    answer: 1,
    explanation: 'O acumulador é um objeto que soma a ocorrência de cada valor, e sim aparece duas vezes.'
  },

  {
    level: 'avancado',
    category: 'hoisting',
    type: 'multiple',
    difficulty: 3,
    question: 'O que é impresso?',
    code: 'console.log(contador);\nvar contador = 3;',
    options: ['3', 'undefined', 'ReferenceError', 'null'],
    answer: 1,
    explanation: 'A declaração com var sobe para o topo do escopo, mas a atribuição fica no lugar, então o valor ainda é undefined.'
  },
  {
    level: 'avancado',
    category: 'hoisting',
    type: 'multiple',
    difficulty: 4,
    question: 'O que acontece?',
    code: 'console.log(total);\nlet total = 3;',
    options: ['Imprime undefined', 'Imprime 3', 'Lança ReferenceError', 'Imprime null'],
    answer: 2,
    explanation: 'let e const ficam na zona morta temporal até a linha da declaração, então o acesso antecipado lança ReferenceError.'
  },
  {
    level: 'avancado',
    category: 'closure',
    type: 'input',
    difficulty: 3,
    question: 'Qual número é impresso?',
    code: 'function criarContador() {\n  let total = 0;\n  return () => {\n    total += 1;\n    return total;\n  };\n}\nconst contar = criarContador();\ncontar();\ncontar();\nconsole.log(contar());',
    answer: '3',
    accept: ['3'],
    explanation: 'A função interna mantém acesso à variável total mesmo depois de criarContador terminar. Isso é uma closure.'
  },
  {
    level: 'avancado',
    category: 'closure',
    type: 'multiple',
    difficulty: 4,
    question: 'O que é impresso?',
    code: 'for (var i = 0; i < 3; i += 1) {\n  setTimeout(() => console.log(i), 0);\n}',
    options: ['0 1 2', '3 3 3', '0 0 0', '2 2 2'],
    answer: 1,
    explanation: 'var tem escopo de função, então as três callbacks compartilham a mesma variável, que vale 3 no fim do laço. Com let a saída seria 0 1 2.'
  },
  {
    level: 'avancado',
    category: 'escopo',
    type: 'multiple',
    difficulty: 3,
    question: 'Qual afirmação descreve corretamente a diferença entre var e let?',
    options: ['var tem escopo de bloco e let tem escopo de função', 'var tem escopo de função e let tem escopo de bloco', 'Os dois têm escopo de bloco', 'Os dois têm escopo global sempre'],
    answer: 1,
    explanation: 'var vaza para fora de blocos como if e for, enquanto let e const ficam presos ao bloco onde foram declarados.'
  },
  {
    level: 'avancado',
    category: 'assincrono',
    type: 'multiple',
    difficulty: 3,
    question: 'Qual é a ordem das mensagens?',
    code: 'console.log("A");\nsetTimeout(() => console.log("B"), 0);\nconsole.log("C");',
    options: ['A B C', 'A C B', 'B A C', 'C A B'],
    answer: 1,
    explanation: 'setTimeout agenda a callback para depois que a pilha esvaziar, mesmo com atraso 0.'
  },
  {
    level: 'avancado',
    category: 'promises',
    type: 'multiple',
    difficulty: 4,
    question: 'O que é impresso?',
    code: 'async function carregar() {\n  return 10;\n}\nconsole.log(carregar());',
    options: ['10', 'Uma Promise', 'undefined', 'SyntaxError'],
    answer: 1,
    explanation: 'Toda função async devolve uma Promise. Para ver o 10 é preciso usar await ou .then.'
  },
  {
    level: 'avancado',
    category: 'promises',
    type: 'multiple',
    difficulty: 4,
    question: 'Você dispara três requisições com Promise.all e uma delas falha. O que acontece?',
    options: ['O resultado traz as duas que deram certo', 'A Promise inteira rejeita no primeiro erro', 'A falha é ignorada silenciosamente', 'As outras duas são canceladas automaticamente'],
    answer: 1,
    explanation: 'Promise.all rejeita assim que uma falha. Quando você quer o resultado de todas, use Promise.allSettled.'
  },
  {
    level: 'avancado',
    category: 'fetch',
    type: 'multiple',
    difficulty: 4,
    question: 'A API respondeu 404. Por que o bloco catch não é executado?',
    code: 'try {\n  const resposta = await fetch("/api/itens");\n  const dados = await resposta.json();\n} catch (erro) {\n  console.log("falhou");\n}',
    options: ['Porque faltou async na função', 'Porque fetch só rejeita em falha de rede, não em status de erro', 'Porque 404 é considerado sucesso pelo servidor', 'Porque json() engole o erro'],
    answer: 1,
    explanation: 'fetch resolve mesmo com 404 ou 500. É preciso checar resposta.ok e lançar o erro manualmente.'
  },
  {
    level: 'avancado',
    category: 'fetch',
    type: 'multiple',
    difficulty: 3,
    question: 'Por que este código imprime uma Promise em vez dos dados?',
    code: 'const resposta = await fetch("/api/itens");\nconsole.log(resposta.json());',
    options: ['json() é assíncrono e também precisa de await', 'fetch precisa de dois awaits seguidos', 'resposta já é o corpo da requisição', 'json() só funciona dentro de then'],
    answer: 0,
    explanation: 'resposta.json() lê o corpo de forma assíncrona e devolve uma Promise que precisa ser aguardada.'
  },
  {
    level: 'avancado',
    category: 'erros',
    type: 'multiple',
    difficulty: 4,
    question: 'Qual é a saída completa?',
    code: 'function ler() {\n  try {\n    throw new Error("falhou");\n  } catch (erro) {\n    return "capturado";\n  } finally {\n    console.log("fim");\n  }\n}\nconsole.log(ler());',
    options: ['fim e depois capturado', 'capturado e depois fim', 'Apenas capturado', 'Apenas fim'],
    answer: 0,
    explanation: 'O finally roda antes de a função devolver o valor, então fim aparece primeiro.'
  },
  {
    level: 'avancado',
    category: 'destructuring',
    type: 'input',
    difficulty: 4,
    question: 'Qual texto é impresso?',
    code: 'const { titulo = "Sem nome" } = { autor: "Ana" };\nconsole.log(titulo);',
    answer: 'Sem nome',
    accept: ['sem nome'],
    explanation: 'Como a propriedade titulo não existe no objeto, o valor padrão do destructuring assume.'
  },
  {
    level: 'avancado',
    category: 'destructuring',
    type: 'input',
    difficulty: 3,
    question: 'Qual valor é impresso?',
    code: 'const usuario = { nome: "Ana", idade: 30 };\nconst { nome: apelido } = usuario;\nconsole.log(apelido);',
    answer: 'Ana',
    accept: ['ana'],
    explanation: 'A sintaxe nome: apelido extrai a propriedade nome e guarda em uma variável com outro nome.'
  },
  {
    level: 'avancado',
    category: 'spread',
    type: 'multiple',
    difficulty: 4,
    question: 'O que é impresso?',
    code: 'const base = { config: { som: true } };\nconst copia = { ...base };\ncopia.config.som = false;\nconsole.log(base.config.som);',
    options: ['true', 'false', 'undefined', 'TypeError'],
    answer: 1,
    explanation: 'O spread faz cópia rasa: o objeto interno continua sendo a mesma referência nos dois lugares.'
  },
  {
    level: 'avancado',
    category: 'spread',
    type: 'multiple',
    difficulty: 3,
    question: 'O que é impresso?',
    code: 'const padrao = { som: true, tela: "janela" };\nconst usuario = { tela: "cheia" };\nconsole.log({ ...padrao, ...usuario }.tela);',
    options: ['janela', 'cheia', 'undefined', 'Um array com os dois valores'],
    answer: 1,
    explanation: 'Quando há chaves repetidas, o último objeto espalhado sobrescreve os anteriores.'
  },
  {
    level: 'avancado',
    category: 'rest',
    type: 'input',
    difficulty: 3,
    question: 'Qual número é impresso?',
    code: 'function somar(...valores) {\n  return valores.length;\n}\nconsole.log(somar(1, 2, 3));',
    answer: '3',
    accept: ['3'],
    explanation: 'O parâmetro rest agrupa todos os argumentos restantes em um array de verdade.'
  },
  {
    level: 'avancado',
    category: 'this',
    type: 'multiple',
    difficulty: 4,
    question: 'O que é impresso?',
    code: 'const painel = {\n  total: 10,\n  mostrar: () => this.total\n};\nconsole.log(painel.mostrar());',
    options: ['10', 'undefined', 'null', 'TypeError'],
    answer: 1,
    explanation: 'Arrow functions não criam o próprio this: ele vem do escopo externo, que não é o objeto painel.'
  },
  {
    level: 'avancado',
    category: 'this',
    type: 'multiple',
    difficulty: 4,
    question: 'O método foi guardado em uma variável e perdeu o contexto. Qual linha resolve o problema?',
    code: 'const contador = {\n  total: 5,\n  ler() {\n    return this.total;\n  }\n};\nconst ler = contador.ler;',
    options: ['const ler = contador.ler.bind(contador);', 'const ler = contador.ler();', 'const ler = new contador.ler();', 'const ler = () => contador.ler;'],
    answer: 0,
    explanation: 'bind fixa o valor de this. Uma arrow function chamando contador.ler() também resolveria.'
  },
  {
    level: 'avancado',
    category: 'hof',
    type: 'input',
    difficulty: 4,
    question: 'Qual número é impresso?',
    code: 'const multiplicar = (fator) => (valor) => valor * fator;\nconsole.log(multiplicar(3)(4));',
    answer: '12',
    accept: ['12'],
    explanation: 'A primeira chamada devolve uma função que lembra o fator 3, e a segunda aplica esse fator ao 4.'
  },
  {
    level: 'avancado',
    category: 'modulos',
    type: 'multiple',
    difficulty: 3,
    question: 'O que é necessário para usar import e export em um arquivo carregado pelo navegador?',
    options: ['Nada, funciona em qualquer script', 'A tag precisa ser <script type="module">', 'É obrigatório usar um empacotador', 'Os arquivos precisam terminar em .mjs'],
    answer: 1,
    explanation: 'Sem type="module" o navegador trata o arquivo como script clássico e a palavra import gera erro de sintaxe.'
  },
  {
    level: 'avancado',
    category: 'modulos',
    type: 'multiple',
    difficulty: 4,
    question: 'O módulo usa export default function iniciar() {}. Qual import está correto?',
    options: ['import { iniciar } from "./app.js";', 'import iniciar from "./app.js";', 'import * iniciar from "./app.js";', 'import default iniciar from "./app.js";'],
    answer: 1,
    explanation: 'A exportação padrão é importada sem chaves e pode receber qualquer nome no arquivo que importa.'
  },
  {
    level: 'avancado',
    category: 'operadores',
    type: 'multiple',
    difficulty: 4,
    question: 'Quais valores aparecem, na ordem?',
    code: 'const limite = 0;\nconsole.log(limite || 10);\nconsole.log(limite ?? 10);',
    options: ['10 e 0', '0 e 10', '10 e 10', '0 e 0'],
    answer: 0,
    explanation: '|| troca qualquer valor falsy, inclusive 0. ?? só entra em ação com null ou undefined.'
  },
  {
    level: 'avancado',
    category: 'operadores',
    type: 'input',
    difficulty: 3,
    question: 'Qual valor é impresso?',
    code: 'const dados = {};\nconsole.log(dados.usuario?.nome);',
    answer: 'undefined',
    accept: ['undefined'],
    explanation: 'O encadeamento opcional interrompe a leitura quando encontra null ou undefined, devolvendo undefined em vez de lançar erro.'
  },
  {
    level: 'avancado',
    category: 'metodos',
    type: 'multiple',
    difficulty: 5,
    question: 'O que é impresso?',
    code: 'console.log(["1", "2", "3"].map(parseInt));',
    options: ['[1, 2, 3]', '[1, NaN, NaN]', '["1", "2", "3"]', '[NaN, NaN, NaN]'],
    answer: 1,
    explanation: 'map passa valor e índice, e parseInt usa o segundo argumento como base: parseInt("2", 1) e parseInt("3", 2) dão NaN.'
  },
  {
    level: 'avancado',
    category: 'imutabilidade',
    type: 'multiple',
    difficulty: 4,
    question: 'O que é impresso?',
    code: 'const config = Object.freeze({ tela: { cheia: false } });\nconfig.tela.cheia = true;\nconsole.log(config.tela.cheia);',
    options: ['false', 'true', 'undefined', 'TypeError'],
    answer: 1,
    explanation: 'Object.freeze congela apenas o primeiro nível. Objetos internos continuam livres para alteração.'
  },
  {
    level: 'avancado',
    category: 'dom',
    type: 'multiple',
    difficulty: 4,
    question: 'Você precisa inserir 500 itens em uma lista. Qual abordagem evita 500 reflows?',
    options: ['Chamar appendChild dentro do laço', 'Usar innerHTML += a cada item', 'Montar um DocumentFragment e inserir uma única vez', 'Criar os elementos e inserir com setTimeout'],
    answer: 2,
    explanation: 'O fragmento fica fora da árvore renderizada, então o navegador recalcula o layout apenas na inserção final.'
  },
  {
    level: 'avancado',
    category: 'eventos',
    type: 'multiple',
    difficulty: 4,
    question: 'Um clique em um botão dentro de um card também dispara o handler do card. Como impedir isso no handler do botão?',
    options: ['event.preventDefault()', 'event.stopPropagation()', 'return false no final', 'removeEventListener no card'],
    answer: 1,
    explanation: 'stopPropagation interrompe a subida do evento pela árvore. preventDefault só cancela a ação padrão do navegador.'
  },
  {
    level: 'avancado',
    category: 'tipos',
    type: 'input',
    difficulty: 3,
    question: 'Qual texto é impresso?',
    code: 'console.log(typeof function () {});',
    answer: 'function',
    accept: ['function'],
    explanation: 'Funções são objetos, mas typeof tem um caso especial e devolve function.'
  },
  {
    level: 'avancado',
    category: 'assincrono',
    type: 'multiple',
    difficulty: 4,
    question: 'Como capturar o erro de uma Promise rejeitada dentro de uma função async?',
    options: ['Envolver o await em try/catch', 'Usar um if antes do await', 'Chamar process.exit no erro', 'Não é possível capturar'],
    answer: 0,
    explanation: 'Com await a rejeição vira uma exceção comum, então try/catch funciona normalmente. Com .then usa-se .catch.'
  },

  {
    level: 'senior',
    category: 'eventloop',
    type: 'multiple',
    difficulty: 5,
    question: 'Qual é a ordem exata dos números impressos?',
    code: 'console.log(1);\nsetTimeout(() => console.log(2));\nqueueMicrotask(() => console.log(3));\nPromise.resolve().then(() => console.log(4));\nconsole.log(5);',
    options: ['1 5 3 4 2', '1 5 2 3 4', '1 2 3 4 5', '1 5 4 3 2'],
    answer: 0,
    explanation: 'Primeiro o código síncrono, depois toda a fila de microtasks na ordem em que foi agendada e só então a macrotask do setTimeout.'
  },
  {
    level: 'senior',
    category: 'eventloop',
    type: 'multiple',
    difficulty: 5,
    question: 'Qual é a ordem das letras?',
    code: 'async function iniciar() {\n  console.log("A");\n  await null;\n  console.log("B");\n}\niniciar();\nconsole.log("C");',
    options: ['A B C', 'A C B', 'C A B', 'B A C'],
    answer: 1,
    explanation: 'O corpo da função async roda de forma síncrona até o primeiro await. O que vem depois é agendado como microtask.'
  },
  {
    level: 'senior',
    category: 'eventloop',
    type: 'multiple',
    difficulty: 5,
    question: 'Uma microtask que agenda outra microtask a cada execução é criada. Qual é a consequência?',
    options: ['O navegador alterna entre elas e o render normalmente', 'A fila nunca esvazia e a interface congela', 'As microtasks viram macrotasks depois de mil execuções', 'O event loop ignora as repetidas'],
    answer: 1,
    explanation: 'A fila de microtasks precisa esvaziar antes do próximo render ou macrotask. Realimentá-la trava a página.'
  },
  {
    level: 'senior',
    category: 'eventloop',
    type: 'multiple',
    difficulty: 4,
    question: 'O que setTimeout(callback, 0) realmente garante?',
    options: ['Execução imediata, antes de qualquer outra coisa', 'Execução após a pilha esvaziar e as microtasks rodarem', 'Execução exatamente em 0 milissegundos', 'Execução em uma thread paralela'],
    answer: 1,
    explanation: 'O atraso é apenas o tempo mínimo até a callback entrar na fila de macrotasks, que só roda com a pilha vazia.'
  },
  {
    level: 'senior',
    category: 'callstack',
    type: 'multiple',
    difficulty: 4,
    question: 'Uma função recursiva sem caso de parada é executada. Qual erro aparece?',
    options: ['TypeError', 'RangeError de estouro da pilha', 'ReferenceError', 'SyntaxError'],
    answer: 1,
    explanation: 'Cada chamada empilha um frame. Quando a pilha estoura, o motor lança RangeError: Maximum call stack size exceeded.'
  },
  {
    level: 'senior',
    category: 'erros',
    type: 'multiple',
    difficulty: 5,
    question: 'Por que a mensagem capturado nunca aparece?',
    code: 'try {\n  setTimeout(() => {\n    throw new Error("falhou");\n  }, 0);\n} catch (erro) {\n  console.log("capturado");\n}',
    options: ['O erro acontece em outra volta do event loop, fora do try', 'setTimeout não lança erros', 'Falta declarar o catch como async', 'O erro é engolido pelo motor'],
    answer: 0,
    explanation: 'Quando a callback roda, o bloco try já terminou. O tratamento precisa ficar dentro da própria callback.'
  },
  {
    level: 'senior',
    category: 'promises',
    type: 'multiple',
    difficulty: 5,
    question: 'Por que dados chega como undefined?',
    code: 'buscar()\n  .then(resposta => {\n    resposta.json();\n  })\n  .then(dados => console.log(dados));',
    options: ['json() é síncrono e não deveria ser usado ali', 'O primeiro then não retorna a Promise de json()', 'Faltou um catch no fim da cadeia', 'then só aceita uma função por cadeia'],
    answer: 1,
    explanation: 'Com chaves o corpo precisa de return. Sem ele, o then devolve undefined e quebra o encadeamento.'
  },
  {
    level: 'senior',
    category: 'performance',
    type: 'multiple',
    difficulty: 5,
    question: 'Três requisições independentes levam 1 segundo cada. Qual implementação termina em cerca de 1 segundo?',
    options: ['await uma depois da outra em sequência', 'Promise.all com as três chamadas iniciadas juntas', 'Um for...of com await dentro', 'Três setTimeout encadeados'],
    answer: 1,
    explanation: 'Sequências com await esperam uma de cada vez. Promise.all dispara tudo em paralelo e aguarda o conjunto.'
  },
  {
    level: 'senior',
    category: 'assincrono',
    type: 'multiple',
    difficulty: 5,
    question: 'O usuário digita rápido em um campo de busca e respostas antigas chegam depois das novas, sobrescrevendo a lista. Qual é a melhor solução?',
    options: ['Aumentar o tempo do debounce e aceitar o risco', 'Cancelar a requisição anterior com AbortController ou descartar respostas fora de ordem', 'Usar try/catch em volta do fetch', 'Trocar fetch por XMLHttpRequest'],
    answer: 1,
    explanation: 'É uma condição de corrida: só a resposta da última requisição deve ser aplicada, e o AbortController resolve isso na origem.'
  },
  {
    level: 'senior',
    category: 'memoria',
    type: 'multiple',
    difficulty: 5,
    question: 'Um componente é criado e destruído várias vezes e a memória só cresce. Qual causa é a mais provável?',
    options: ['Uso de const em vez de let', 'Listeners e intervalos registrados e nunca removidos', 'Muitas funções puras no arquivo', 'Uso de template literals'],
    answer: 1,
    explanation: 'Listeners e setInterval mantêm referências vivas para closures e nós do DOM, impedindo a coleta de lixo.'
  },
  {
    level: 'senior',
    category: 'memoria',
    type: 'multiple',
    difficulty: 5,
    question: 'Você precisa guardar dados extras associados a elementos do DOM sem impedir que eles sejam liberados da memória. O que usar?',
    options: ['Um objeto comum indexado por id', 'Um array de pares', 'Um WeakMap com o elemento como chave', 'localStorage'],
    answer: 2,
    explanation: 'As chaves de um WeakMap são referências fracas: quando o elemento é removido, a entrada some junto.'
  },
  {
    level: 'senior',
    category: 'performance',
    type: 'multiple',
    difficulty: 5,
    question: 'Por que este laço deixa a página lenta?',
    code: 'itens.forEach(item => {\n  item.style.height = "40px";\n  console.log(item.offsetHeight);\n});',
    options: ['forEach é mais lento que for', 'Escrever e logo depois ler força um reflow a cada volta', 'console.log bloqueia a thread', 'style só deveria ser alterado com classes'],
    answer: 1,
    explanation: 'É layout thrashing. Leia todas as medidas primeiro e depois aplique as escritas em lote.'
  },
  {
    level: 'senior',
    category: 'performance',
    type: 'multiple',
    difficulty: 4,
    question: 'Uma tabela com cinco mil linhas precisa responder a cliques em cada linha. Qual abordagem escala melhor?',
    options: ['Registrar um listener em cada linha', 'Registrar um listener na tabela e identificar a linha por event.target', 'Usar onclick no HTML de cada linha', 'Recriar os listeners a cada render'],
    answer: 1,
    explanation: 'A delegação usa um único ouvinte, gasta menos memória e continua funcionando para linhas criadas depois.'
  },
  {
    level: 'senior',
    category: 'performance',
    type: 'multiple',
    difficulty: 4,
    question: 'Qual é a forma correta de animar um elemento quadro a quadro em sincronia com o navegador?',
    options: ['setInterval com 16 milissegundos', 'requestAnimationFrame', 'Um while medindo Date.now', 'setTimeout recursivo com 1 milissegundo'],
    answer: 1,
    explanation: 'requestAnimationFrame acompanha a taxa de atualização da tela e pausa quando a aba fica em segundo plano.'
  },
  {
    level: 'senior',
    category: 'performance',
    type: 'multiple',
    difficulty: 5,
    question: 'Um cálculo pesado de vários segundos congela a interface. Qual é a solução adequada?',
    options: ['Dividir com setTimeout de 0 em 0', 'Mover o cálculo para um Web Worker', 'Marcar a função como async', 'Envolver o cálculo em uma Promise'],
    answer: 1,
    explanation: 'async e Promise não criam paralelismo: o trabalho continua na thread principal. O Worker roda em outra thread de verdade.'
  },
  {
    level: 'senior',
    category: 'performance',
    type: 'multiple',
    difficulty: 5,
    question: 'Procurar duplicados comparando cada item com todos os outros é O(n²). Qual estrutura reduz isso para O(n)?',
    options: ['Um array auxiliar com indexOf', 'Um Set guardando o que já foi visto', 'Ordenar com sort antes do laço duplo', 'Um objeto com JSON.stringify em cada volta'],
    answer: 1,
    explanation: 'Set tem busca em tempo praticamente constante, então uma única passagem resolve. indexOf dentro do laço mantém o custo quadrático.'
  },
  {
    level: 'senior',
    category: 'estado',
    type: 'multiple',
    difficulty: 5,
    question: 'Qual linha atualiza o estado sem alterar o objeto anterior?',
    options: ['estado.itens.push(item); return estado;', 'return { ...estado, itens: [...estado.itens, item] };', 'estado.itens = estado.itens.concat(item); return estado;', 'return Object.assign(estado, { total: 1 });'],
    answer: 1,
    explanation: 'As outras opções mutam o objeto recebido, o que quebra comparações por referência e o histórico de estados.'
  },
  {
    level: 'senior',
    category: 'estado',
    type: 'multiple',
    difficulty: 5,
    question: 'O estado é { usuario: { perfil: { tema: "claro" } } }. Qual expressão troca apenas o tema mantendo a imutabilidade?',
    options: ['{ ...estado, usuario: { perfil: { tema: "escuro" } } }', '{ ...estado, usuario: { ...estado.usuario, perfil: { ...estado.usuario.perfil, tema: "escuro" } } }', 'Object.assign(estado.usuario.perfil, { tema: "escuro" })', '{ ...estado, tema: "escuro" }'],
    answer: 1,
    explanation: 'Cada nível precisa ser copiado. A primeira opção descartaria as outras propriedades de usuario e de perfil.'
  },
  {
    level: 'senior',
    category: 'bugs',
    type: 'multiple',
    difficulty: 5,
    question: 'Por que alguns itens inválidos sobrevivem a esta limpeza?',
    code: 'itens.forEach((item, indice) => {\n  if (!item.valido) {\n    itens.splice(indice, 1);\n  }\n});',
    options: ['forEach não aceita dois parâmetros', 'Remover durante a iteração desloca os índices e pula elementos', 'splice não remove o item correto', 'O array precisa ser const'],
    answer: 1,
    explanation: 'Mutação durante a iteração é uma armadilha clássica. O correto é gerar um novo array com filter.'
  },
  {
    level: 'senior',
    category: 'bugs',
    type: 'multiple',
    difficulty: 5,
    question: 'Por que esta função devolve 0 mesmo com valores válidos?',
    code: 'let total = 0;\nfunction registrar(valores) {\n  valores.forEach(async (valor) => {\n    total += await calcular(valor);\n  });\n  return total;\n}',
    options: ['forEach não espera as callbacks assíncronas terminarem', 'total precisa ser const', 'await não funciona dentro de arrow functions', 'calcular precisa retornar um número síncrono'],
    answer: 0,
    explanation: 'forEach ignora as Promises devolvidas. Use for...of com await ou Promise.all sobre um map.'
  },
  {
    level: 'senior',
    category: 'clonagem',
    type: 'multiple',
    difficulty: 5,
    question: 'O que se perde ao clonar um objeto com JSON.parse(JSON.stringify(objeto))?',
    options: ['Nada, é uma cópia profunda perfeita', 'Datas viram texto e funções e undefined desaparecem', 'Apenas a ordem das chaves', 'Somente os arrays aninhados'],
    answer: 1,
    explanation: 'Esse truque também quebra com referências circulares. structuredClone cobre a maioria desses casos.'
  },
  {
    level: 'senior',
    category: 'seguranca',
    type: 'multiple',
    difficulty: 5,
    question: 'Um comentário enviado pelo usuário é inserido com elemento.innerHTML = comentario. Qual é o risco e a correção?',
    options: ['Nenhum risco, innerHTML é seguro por padrão', 'Risco de XSS: usar textContent ou sanitizar antes de inserir', 'Risco apenas de quebra de layout: usar CSS', 'Risco de lentidão: usar innerText'],
    answer: 1,
    explanation: 'innerHTML interpreta tags e atributos de evento, permitindo execução de script. textContent trata tudo como texto.'
  },
  {
    level: 'senior',
    category: 'seguranca',
    type: 'multiple',
    difficulty: 5,
    question: 'Por que executar uma expressão vinda do usuário com eval é perigoso?',
    options: ['eval é apenas lento', 'O texto roda com todos os privilégios da página, incluindo acesso a cookies e tokens', 'eval não funciona em navegadores modernos', 'eval só aceita números'],
    answer: 1,
    explanation: 'eval e new Function transformam dados em código. Para expressões controladas, use um parser próprio ou uma lista de operações permitidas.'
  },
  {
    level: 'senior',
    category: 'seguranca',
    type: 'multiple',
    difficulty: 4,
    question: 'Qual é a principal desvantagem de guardar um token de acesso no localStorage?',
    options: ['O espaço é limitado a 5 megabytes', 'Qualquer script da página consegue ler o valor, então um XSS rouba a sessão', 'O valor expira ao fechar a aba', 'Só aceita números'],
    answer: 1,
    explanation: 'localStorage é acessível por JavaScript. Cookies com HttpOnly ficam fora do alcance de scripts injetados.'
  },
  {
    level: 'senior',
    category: 'padroes',
    type: 'multiple',
    difficulty: 4,
    question: 'Qual padrão este trecho representa?',
    code: 'const Placar = (() => {\n  let total = 0;\n  return {\n    somar: (pontos) => {\n      total += pontos;\n    },\n    ler: () => total\n  };\n})();',
    options: ['Observer', 'Módulo com estado privado', 'Factory', 'Singleton de classe'],
    answer: 1,
    explanation: 'A IIFE cria um escopo fechado e expõe só a API pública, mantendo total inacessível de fora.'
  },
  {
    level: 'senior',
    category: 'padroes',
    type: 'multiple',
    difficulty: 4,
    question: 'Um módulo mantém uma lista de funções interessadas e avisa todas quando o estado muda. Qual padrão é esse?',
    options: ['Observer, também chamado de publicador e assinante', 'Singleton', 'Decorator', 'Adapter'],
    answer: 0,
    explanation: 'O Observer desacopla quem produz o evento de quem reage a ele, base de sistemas de eventos e de estado reativo.'
  },
  {
    level: 'senior',
    category: 'refatoracao',
    type: 'multiple',
    difficulty: 4,
    question: 'Qual refatoração reduz o aninhamento desta função sem mudar o comportamento?',
    code: 'function salvar(usuario) {\n  if (usuario) {\n    if (usuario.ativo) {\n      if (usuario.email) {\n        return enviar(usuario);\n      }\n    }\n  }\n  return null;\n}',
    options: ['Trocar os if por switch', 'Usar cláusulas de guarda com return antecipado', 'Transformar a função em async', 'Juntar tudo em um operador ternário longo'],
    answer: 1,
    explanation: 'Retornar cedo nos casos inválidos deixa o caminho principal no primeiro nível e facilita a leitura.'
  },
  {
    level: 'senior',
    category: 'arquitetura',
    type: 'multiple',
    difficulty: 5,
    question: 'Uma função calcula o desconto, grava no servidor e atualiza o HTML. Qual é o principal problema de arquitetura?',
    options: ['O nome da função está pequeno demais', 'Ela acumula regra de negócio, acesso a dados e renderização, ficando difícil de testar e reaproveitar', 'Deveria usar var em vez de const', 'Precisa ser assíncrona'],
    answer: 1,
    explanation: 'Separar cálculo puro, acesso a dados e interface permite testar a regra isoladamente e trocar a camada visual sem risco.'
  },
  {
    level: 'senior',
    category: 'bugs',
    type: 'multiple',
    difficulty: 5,
    question: 'Uma função de ordenação recebe o estado e devolve a lista ordenada, mas a lista original também aparece ordenada na interface. Por quê?',
    options: ['sort devolve uma cópia e o bug está em outro lugar', 'sort ordena o próprio array recebido, então o estado foi mutado', 'A comparação está invertida', 'A interface guarda cache da lista'],
    answer: 1,
    explanation: 'Array.prototype.sort altera o array original. Em estado imutável, ordene uma cópia com [...lista].sort().'
  },
  {
    level: 'senior',
    category: 'performance',
    type: 'multiple',
    difficulty: 5,
    question: 'Um campo de busca dispara uma requisição a cada tecla e a rolagem recalcula posições a cada evento. Qual combinação resolve os dois casos?',
    options: ['debounce na busca e throttle na rolagem', 'throttle na busca e debounce na rolagem', 'debounce nos dois', 'throttle nos dois'],
    answer: 0,
    explanation: 'Debounce espera a pausa e serve para a digitação. Throttle limita a frequência e mantém a rolagem respondendo em intervalos fixos.'
  },

  {
    level: 'iniciante',
    category: 'variaveis',
    type: 'complete',
    difficulty: 1,
    question: 'Complete a declaração de um valor que nunca muda.',
    code: '___ PI = 3.14;',
    answer: 'const',
    accept: ['const'],
    explanation: 'const cria uma ligação que não aceita reatribuição, ideal para valores fixos.'
  },
  {
    level: 'iniciante',
    category: 'operadores',
    type: 'complete',
    difficulty: 1,
    question: 'Complete para somar 3 ao total usando a forma curta.',
    code: 'let total = 5;\ntotal ___ 3;\nconsole.log(total);',
    answer: '+=',
    accept: ['+='],
    explanation: 'total += 3 é a forma curta de total = total + 3.'
  },
  {
    level: 'iniciante',
    category: 'funcoes',
    type: 'complete',
    difficulty: 1,
    question: 'Complete para a função devolver o dobro do valor.',
    code: 'function dobro(valor) {\n  ___ valor * 2;\n}',
    answer: 'return',
    accept: ['return'],
    explanation: 'Sem return a função executa mas devolve undefined.'
  },
  {
    level: 'iniciante',
    category: 'comparacao',
    type: 'complete',
    difficulty: 1,
    question: 'Complete para o bloco rodar quando a idade for 18 ou mais.',
    code: 'if (idade ___ 18) {\n  console.log("maior");\n}',
    answer: '>=',
    accept: ['>='],
    explanation: '>= cobre o caso de igualdade, então 18 também entra na condição.'
  },
  {
    level: 'iniciante',
    category: 'arrays',
    type: 'complete',
    difficulty: 1,
    question: 'Complete para adicionar o item no fim do array.',
    code: 'const cores = ["azul"];\ncores.___("verde");',
    answer: 'push',
    accept: ['push'],
    explanation: 'push insere no fim e devolve o novo tamanho do array.'
  },
  {
    level: 'iniciante',
    category: 'strings',
    type: 'complete',
    difficulty: 2,
    question: 'Complete o template literal para mostrar a idade.',
    code: 'const idade = 20;\nconsole.log(`Tenho ${___} anos`);',
    answer: 'idade',
    accept: ['idade'],
    explanation: 'Dentro de ${} vai qualquer expressão, inclusive o nome da variável.'
  },
  {
    level: 'iniciante',
    category: 'tipos',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para converter o texto em número antes de somar.',
    code: 'const nota = "8";\nconsole.log(___(nota) + 2);',
    answer: 'Number',
    accept: ['number', 'parseint', 'parsefloat'],
    explanation: 'Sem a conversão o + concatena e o resultado vira o texto 82.'
  },
  {
    level: 'iniciante',
    category: 'comparacao',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para comparar valor e tipo ao mesmo tempo.',
    code: 'if (entrada ___ 10) {\n  console.log("dez");\n}',
    answer: '===',
    accept: ['==='],
    explanation: '=== não faz conversão automática, então "10" não passa na comparação.'
  },
  {
    level: 'iniciante',
    category: 'arrays',
    type: 'complete',
    difficulty: 1,
    question: 'Complete para mostrar quantos itens o array tem.',
    code: 'const lista = ["a", "b", "c"];\nconsole.log(lista___);',
    answer: '.length',
    accept: ['.length', 'length'],
    explanation: 'length é uma propriedade, por isso não leva parênteses.'
  },
  {
    level: 'iniciante',
    category: 'loops',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para o laço repetir exatamente cinco vezes.',
    code: 'for (let i = 0; i ___ 5; i += 1) {\n  console.log(i);\n}',
    answer: '<',
    accept: ['<'],
    explanation: 'Começando em 0, a condição i < 5 dá as cinco voltas de 0 a 4.'
  },
  {
    level: 'iniciante',
    category: 'arrays',
    type: 'complete',
    difficulty: 1,
    question: 'Complete para pegar o primeiro item da lista.',
    code: 'const primeiro = lista[___];',
    answer: '0',
    accept: ['0'],
    explanation: 'O índice do primeiro elemento é sempre 0.'
  },
  {
    level: 'iniciante',
    category: 'strings',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para imprimir o texto todo em maiúsculas.',
    code: 'const texto = "javascript";\nconsole.log(texto.___());',
    answer: 'toUpperCase',
    accept: ['touppercase'],
    explanation: 'toUpperCase devolve um novo texto e não altera a string original.'
  },
  {
    level: 'iniciante',
    category: 'funcoes',
    type: 'complete',
    difficulty: 2,
    question: 'Complete a arrow function que soma dois valores.',
    code: 'const soma = (a, b) ___ a + b;',
    answer: '=>',
    accept: ['=>'],
    explanation: 'Sem chaves depois da seta, o valor da expressão já é retornado.'
  },

  {
    level: 'intermediario',
    category: 'metodos',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para criar um novo array com cada item dobrado.',
    code: 'const dobros = numeros.___(n => n * 2);',
    answer: 'map',
    accept: ['map'],
    explanation: 'map transforma cada item e devolve um array do mesmo tamanho.'
  },
  {
    level: 'intermediario',
    category: 'metodos',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para manter apenas os números maiores que 10.',
    code: 'const grandes = numeros.___(n => n > 10);',
    answer: 'filter',
    accept: ['filter'],
    explanation: 'filter devolve um novo array só com os itens que passam no teste.'
  },
  {
    level: 'intermediario',
    category: 'metodos',
    type: 'complete',
    difficulty: 3,
    question: 'Complete para somar todos os valores em um único número.',
    code: 'const total = valores.___((soma, item) => soma + item, 0);',
    answer: 'reduce',
    accept: ['reduce'],
    explanation: 'reduce acumula os itens partindo do valor inicial passado no segundo argumento.'
  },
  {
    level: 'intermediario',
    category: 'metodos',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para pegar o primeiro usuário com id igual a 3.',
    code: 'const achado = usuarios.___(usuario => usuario.id === 3);',
    answer: 'find',
    accept: ['find'],
    explanation: 'find devolve o próprio item, ou undefined quando nenhum combina.'
  },
  {
    level: 'intermediario',
    category: 'eventos',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para executar salvar quando o botão for clicado.',
    code: 'botao.___("click", salvar);',
    answer: 'addEventListener',
    accept: ['addeventlistener'],
    explanation: 'A função é passada por referência, sem parênteses, senão ela executa na hora.'
  },
  {
    level: 'intermediario',
    category: 'dom',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para buscar o elemento com id total.',
    code: 'document.___("#total").textContent = "0";',
    answer: 'querySelector',
    accept: ['queryselector', 'getelementbyid'],
    explanation: 'querySelector aceita qualquer seletor CSS e devolve o primeiro elemento encontrado.'
  },
  {
    level: 'intermediario',
    category: 'formularios',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para impedir que a página recarregue no envio.',
    code: 'formulario.addEventListener("submit", (evento) => {\n  evento.___();\n});',
    answer: 'preventDefault',
    accept: ['preventdefault'],
    explanation: 'preventDefault cancela o comportamento padrão do navegador para aquele evento.'
  },
  {
    level: 'intermediario',
    category: 'loops',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para percorrer os valores da lista.',
    code: 'for (const item ___ lista) {\n  console.log(item);\n}',
    answer: 'of',
    accept: ['of'],
    explanation: 'for...of entrega os valores. for...in entregaria os índices.'
  },
  {
    level: 'intermediario',
    category: 'dom',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para criar um novo elemento de lista.',
    code: 'const item = document.___("li");\nitem.textContent = "Fase 1";',
    answer: 'createElement',
    accept: ['createelement'],
    explanation: 'createElement cria o nó em memória; ele só aparece depois de ser inserido na página.'
  },
  {
    level: 'intermediario',
    category: 'objetos',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para contar quantas propriedades o objeto tem.',
    code: 'console.log(Object.___(config).length);',
    answer: 'keys',
    accept: ['keys'],
    explanation: 'Object.keys devolve um array com os nomes das propriedades próprias.'
  },
  {
    level: 'intermediario',
    category: 'metodos',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para juntar os nomes separados por hífen.',
    code: 'const linha = nomes.___("-");',
    answer: 'join',
    accept: ['join'],
    explanation: 'join transforma o array em uma string usando o separador informado.'
  },
  {
    level: 'intermediario',
    category: 'metodos',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para verificar se a cor existe na lista.',
    code: 'if (lista.___("azul")) {\n  console.log("achou");\n}',
    answer: 'includes',
    accept: ['includes'],
    explanation: 'includes devolve true ou false direto, sem precisar comparar com -1 como no indexOf.'
  },
  {
    level: 'intermediario',
    category: 'dom',
    type: 'complete',
    difficulty: 2,
    question: 'Complete para adicionar a classe quando ela não existir e remover quando existir.',
    code: 'elemento.classList.___("ativo");',
    answer: 'toggle',
    accept: ['toggle'],
    explanation: 'toggle alterna a classe e ainda devolve true quando ela ficou aplicada.'
  },

  {
    level: 'avancado',
    category: 'assincrono',
    type: 'complete',
    difficulty: 3,
    question: 'Complete para esperar a resposta da requisição.',
    code: 'const resposta = ___ fetch("/api/itens");',
    answer: 'await',
    accept: ['await'],
    explanation: 'await só funciona dentro de funções async ou no topo de um módulo.'
  },
  {
    level: 'avancado',
    category: 'rest',
    type: 'complete',
    difficulty: 3,
    question: 'Complete para a função receber qualquer quantidade de argumentos em um array.',
    code: 'function somar(___valores) {\n  return valores.length;\n}',
    answer: '...',
    accept: ['...'],
    explanation: 'O parâmetro rest agrupa os argumentos restantes em um array de verdade.'
  },
  {
    level: 'avancado',
    category: 'spread',
    type: 'complete',
    difficulty: 3,
    question: 'Complete para copiar as propriedades de base no novo objeto.',
    code: 'const copia = { ___base, ativo: true };',
    answer: '...',
    accept: ['...'],
    explanation: 'O spread copia o primeiro nível. Objetos internos continuam compartilhados.'
  },
  {
    level: 'avancado',
    category: 'promises',
    type: 'complete',
    difficulty: 3,
    question: 'Complete para tratar a falha da Promise.',
    code: 'carregar()\n  .then(mostrar)\n  .___(erro => console.log(erro));',
    answer: 'catch',
    accept: ['catch'],
    explanation: 'Sem catch, a rejeição vira um unhandledrejection e some do fluxo.'
  },
  {
    level: 'avancado',
    category: 'fetch',
    type: 'complete',
    difficulty: 3,
    question: 'Complete para ler o corpo da resposta como JSON.',
    code: 'const resposta = await fetch(url);\nconst dados = await resposta.___();',
    answer: 'json',
    accept: ['json'],
    explanation: 'json() também é assíncrono, por isso precisa do segundo await.'
  },
  {
    level: 'avancado',
    category: 'erros',
    type: 'complete',
    difficulty: 3,
    question: 'Complete para capturar o erro lançado dentro do try.',
    code: 'try {\n  salvar();\n} ___ (erro) {\n  console.log(erro);\n}',
    answer: 'catch',
    accept: ['catch'],
    explanation: 'O catch recebe o erro lançado. O finally roda depois, com erro ou sem erro.'
  },
  {
    level: 'avancado',
    category: 'operadores',
    type: 'complete',
    difficulty: 4,
    question: 'Complete para não quebrar quando perfil não existir.',
    code: 'console.log(usuario?.perfil___nome);',
    answer: '?.',
    accept: ['?.'],
    explanation: 'O encadeamento opcional interrompe a leitura e devolve undefined em vez de lançar erro.'
  },
  {
    level: 'avancado',
    category: 'operadores',
    type: 'complete',
    difficulty: 4,
    question: 'Complete para usar o padrão apenas quando entrada for null ou undefined.',
    code: 'const nome = entrada ___ "anonimo";',
    answer: '??',
    accept: ['??'],
    explanation: 'Com || o texto vazio e o 0 também seriam trocados. ?? só reage a null e undefined.'
  },
  {
    level: 'avancado',
    category: 'modulos',
    type: 'complete',
    difficulty: 3,
    question: 'Complete para exportar a função como exportação padrão do módulo.',
    code: 'export ___ function iniciar() {}',
    answer: 'default',
    accept: ['default'],
    explanation: 'A exportação padrão é importada sem chaves e pode receber qualquer nome.'
  },
  {
    level: 'avancado',
    category: 'this',
    type: 'complete',
    difficulty: 4,
    question: 'Complete para o método continuar enxergando o objeto original.',
    code: 'const ler = contador.ler.___(contador);',
    answer: 'bind',
    accept: ['bind'],
    explanation: 'bind devolve uma nova função com o this fixado no objeto informado.'
  },
  {
    level: 'avancado',
    category: 'promises',
    type: 'complete',
    difficulty: 4,
    question: 'Complete para disparar as duas buscas em paralelo e esperar as duas.',
    code: 'const [a, b] = await Promise.___([buscarA(), buscarB()]);',
    answer: 'all',
    accept: ['all'],
    explanation: 'Promise.all espera todas e rejeita no primeiro erro. allSettled esperaria todas sem rejeitar.'
  },
  {
    level: 'avancado',
    category: 'hof',
    type: 'complete',
    difficulty: 4,
    question: 'Complete a função que devolve outra função.',
    code: 'const multiplicar = (fator) => (valor) ___ valor * fator;',
    answer: '=>',
    accept: ['=>'],
    explanation: 'A primeira chamada guarda o fator na closure e devolve a função final.'
  },
  {
    level: 'avancado',
    category: 'closure',
    type: 'complete',
    difficulty: 3,
    question: 'Complete para a variável ficar privada dentro da closure e aceitar mudança.',
    code: 'function criarContador() {\n  ___ total = 0;\n  return () => {\n    total += 1;\n    return total;\n  };\n}',
    answer: 'let',
    accept: ['let'],
    explanation: 'O valor muda a cada chamada, então const não serve. A função interna mantém acesso a ele.'
  },

  {
    level: 'senior',
    category: 'assincrono',
    type: 'complete',
    difficulty: 5,
    question: 'Complete para conseguir cancelar a requisição depois.',
    code: 'const controlador = new ___();\nfetch(url, { signal: controlador.signal });',
    answer: 'AbortController',
    accept: ['abortcontroller'],
    explanation: 'Chamar controlador.abort() cancela a requisição e evita aplicar respostas antigas.'
  },
  {
    level: 'senior',
    category: 'eventloop',
    type: 'complete',
    difficulty: 5,
    question: 'Complete para agendar a função na fila de microtasks sem criar uma Promise.',
    code: '___(() => console.log("microtask"));',
    answer: 'queueMicrotask',
    accept: ['queuemicrotask'],
    explanation: 'Microtasks rodam antes da próxima macrotask e antes do próximo quadro de render.'
  },
  {
    level: 'senior',
    category: 'memoria',
    type: 'complete',
    difficulty: 5,
    question: 'Complete para associar dados ao elemento sem impedir a coleta de lixo.',
    code: 'const dados = new ___();\ndados.set(elemento, { visitas: 1 });',
    answer: 'WeakMap',
    accept: ['weakmap'],
    explanation: 'As chaves de um WeakMap são referências fracas: o elemento removido some junto com a entrada.'
  },
  {
    level: 'senior',
    category: 'seguranca',
    type: 'complete',
    difficulty: 4,
    question: 'Complete para inserir o texto do usuário sem abrir brecha de XSS.',
    code: 'comentario.___ = textoDoUsuario;',
    answer: 'textContent',
    accept: ['textcontent', 'innertext'],
    explanation: 'innerHTML interpretaria tags e atributos de evento. textContent trata tudo como texto.'
  },
  {
    level: 'senior',
    category: 'performance',
    type: 'complete',
    difficulty: 4,
    question: 'Complete o laço de animação sincronizado com a tela.',
    code: 'function animar() {\n  desenhar();\n  ___(animar);\n}',
    answer: 'requestAnimationFrame',
    accept: ['requestanimationframe'],
    explanation: 'requestAnimationFrame acompanha a taxa de atualização e pausa quando a aba sai de foco.'
  },
  {
    level: 'senior',
    category: 'clonagem',
    type: 'complete',
    difficulty: 5,
    question: 'Complete para clonar o estado em profundidade mantendo datas e Map.',
    code: 'const copia = ___(estado);',
    answer: 'structuredClone',
    accept: ['structuredclone'],
    explanation: 'JSON.parse(JSON.stringify(...)) perderia Date, undefined e funções.'
  },
  {
    level: 'senior',
    category: 'estado',
    type: 'complete',
    difficulty: 5,
    question: 'Complete para atualizar o estado sem alterar o objeto anterior.',
    code: 'return { ___estado, total: estado.total + 1 };',
    answer: '...',
    accept: ['...'],
    explanation: 'Um novo objeto preserva a comparação por referência e o histórico de estados.'
  },
  {
    level: 'senior',
    category: 'performance',
    type: 'complete',
    difficulty: 4,
    question: 'Complete para remover duplicados em uma única passagem.',
    code: 'const unicos = [...new ___(lista)];',
    answer: 'Set',
    accept: ['set'],
    explanation: 'Set guarda valores únicos com busca praticamente constante, evitando o laço quadrático.'
  },
  {
    level: 'senior',
    category: 'performance',
    type: 'complete',
    difficulty: 5,
    question: 'Complete para rodar o cálculo pesado fora da thread principal.',
    code: 'const trabalhador = new ___("calculo.js");\ntrabalhador.postMessage(dados);',
    answer: 'Worker',
    accept: ['worker'],
    explanation: 'async e Promise não criam paralelismo: o trabalho continuaria travando a interface.'
  },
  {
    level: 'senior',
    category: 'memoria',
    type: 'complete',
    difficulty: 4,
    question: 'Complete para encerrar o intervalo e evitar vazamento.',
    code: 'const id = setInterval(atualizar, 1000);\n___(id);',
    answer: 'clearInterval',
    accept: ['clearinterval'],
    explanation: 'Um intervalo esquecido mantém vivas as closures e os nós do DOM que ele referencia.'
  },
  {
    level: 'senior',
    category: 'bugs',
    type: 'complete',
    difficulty: 5,
    question: 'Complete para ordenar sem alterar a lista original.',
    code: 'const ordenada = [...lista].___((a, b) => a - b);',
    answer: 'sort',
    accept: ['sort'],
    explanation: 'sort ordena o próprio array, por isso a cópia com spread antes da chamada.'
  },
  {
    level: 'senior',
    category: 'promises',
    type: 'complete',
    difficulty: 4,
    question: 'Complete para esconder o carregamento com sucesso ou com erro.',
    code: 'carregar()\n  .then(mostrar)\n  .catch(avisar)\n  .___(() => esconderCarregando());',
    answer: 'finally',
    accept: ['finally'],
    explanation: 'finally roda nos dois caminhos e não altera o valor que passa pela cadeia.'
  },
  {
    level: 'senior',
    category: 'eventos',
    type: 'complete',
    difficulty: 5,
    question: 'Complete a delegação para descobrir a linha clicada.',
    code: 'tabela.addEventListener("click", (evento) => {\n  const linha = evento.___.closest("tr");\n});',
    answer: 'target',
    accept: ['target'],
    explanation: 'target é quem originou o evento. currentTarget seria sempre a própria tabela.'
  }
];

function registerQuestions(list) {
  if (!Array.isArray(list)) {
    return QUESTION_BANK.length;
  }
  list.forEach((item) => {
    if (item && item.level && item.question) {
      QUESTION_BANK.push(item);
    }
  });
  return QUESTION_BANK.length;
}
